TL/UCP: Check for ucp_memh_pack, if it's not present then disable sliding window and the doca plugin
openucx/ucc pull request #1032
Opened 2024-10-08 20:47 UTC by nsarka

Patch for https://github.com/openucx/ucc/issues/1031

2024-10-09 07:00 UTC, Sergei-Lebedev reviewed
CI error is relevant

2024-10-09 13:23 UTC, janjust approved these changes

2024-10-09 13:33 UTC, janjust commented
@nsarka Something is not quite right

"configure: error: conditional "HAVE_UCP_MEMH_PACK" was never defined.
Usually this means the macro was only invoked conditionally.
Error: Process completed with exit code 1."

2024-10-09 13:34 UTC, janjust requested changes
let's fix the configure error, otherwise, looks good to me

2024-10-15 21:38 UTC, samnordmann approved these changes

2024-10-28 14:05 UTC, janjust approved these changes

2024-12-07 04:21 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2025-01-06 17:41 UTC, closed without merging

2025-01-06 17:42 UTC, nsarka commented
Closing--it was decided in a UCC meeting that instead of merging this PR we will bump the minimum UCX version