TL/UCP: use knomial pattern in gather
openucx/ucc pull request #1044
Opened 2024-10-31 13:42 UTC by Sergei-Lebedev

## What
Use knomial pattern data structure in gather knomial algorithm in TL UCP

## Why ?
part of https://github.com/openucx/ucc/pull/1035
_

2024-11-27 18:48 UTC, manjugv commented
@aamirshafi  Did you have any comments?

2024-11-27 19:19 UTC, aamirshafi commented on src/coll_patterns/sra_knomial.h
@Sergei-Lebedev and I discussed this in our review. The filename has `sra_` in it while this code will also be used to implement other collective algorithms (like `srg`). One suggestion will be to relocate code from this file to `src/coll_patterns/recursive_knomial.h` to have a single knomial pattern file for all collectives. Another option can be to have two separate pattern header files for SRG and SRA.

2024-11-27 19:22 UTC, aamirshafi commented on src/coll_patterns/sra_knomial.h
Also the functions in `sra_knomial.h` use slightly different function names than `recursive_knomial.h`. Note `ucc_kn_g_pattern_init()` vs. `ucc_knomial_pattern_init`.

2024-11-27 19:26 UTC, aamirshafi commented on src/components/tl/ucp/gather/gather_knomial.c
> +            if ((ct != UCC_COLL_TYPE_REDUCE)  &&
Please add a comment why reduce collective is checked for in a gather related file.

2024-11-27 19:32 UTC, aamirshafi requested changes
@Sergei-Lebedev presented this PR in couple of sessions. I have requested a few changes that are inserted as comments: 1) clarify the structure of header files ([recursive_knomial.h](https://github.com/Sergei-Lebedev/ucc/blob/topic/gather_kn_pattern/src/coll_patterns/recursive_knomial.h) and [sra_knomial.h](https://github.com/Sergei-Lebedev/ucc/blob/topic/gather_kn_pattern/src/coll_patterns/sra_knomial.h)), and 2) add a few comments to explain corner-cases.

2024-11-27 19:35 UTC, aamirshafi commented
> @aamirshafi Did you have any comments?

I have added my review @manjugv.

2024-12-04 12:04 UTC, samnordmann approved these changes

2024-12-07 04:21 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2024-12-11 16:22 UTC, aamirshafi commented
@manjugv - this PR looks good to me.

2024-12-12 16:03 UTC, janjust approved these changes

2024-12-13 10:50 UTC, merged