CL/HIER: Add allgatherv
openucx/ucc pull request #1050
Opened 2024-12-02 15:31 UTC by nsarka

This PR adds CL/HIER allgatherv and updates the allgatherv gtest to test non-contiguous dst buffers. It is meant to be used in conjunction with my TL/SHM gatherv implementation.

The algorithm is:
- Node-level gatherv, all sendbufs on the node are put into a scratch buffer
- Leader-level allgatherv on the scratch buffer, the result is put into the dst buffer
- Node-level in-place bcast on the dst buffer
- If the buffer is non-contig, unpack by memcpying the packed buffer into the right displacements

## Comparison Data

2 nodes, 32 PPN on lego-grace cg (1 socket, 72 cores/socket)

Size | UCC after PR (cl_hier + tl_shm + tl_ucp) | UCC before PR (cl_basic + tl_ucp) | HCOLL | %-Gain, After vs. HCOLL | %-Gain, Old vs. HCOLL | %-Gain, Before vs. After
-- | -- | -- | -- | -- | -- | --
1 | 7.37 | 19.88 | 7.41 | 0.54% | -168.29% | 62.93%
2 | 7.81 | 19.75 | 7.47 | -4.55% | -164.39% | 60.46%
4 | 7.62 | 19.79 | 7.65 | 0.39% | -158.69% | 61.50%
8 | 8.35 | 19.78 | 8.13 | -2.71% | -143.30% | 57.79%
16 | 9.49 | 19.8 | 9.44 | -0.53% | -109.75% | 52.07%
32 | 9.34 | 22.91 | 9.67 | 3.41% | -136.92% | 59.23%
64 | 9.17 | 22.96 | 10.03 | 8.57% | -128.91% | 60.06%
128 | 10.47 | 27.55 | 10.88 | 3.77% | -153.22% | 62.00%
256 | 12.68 | 33.37 | 12.46 | -1.77% | -167.82% | 62.00%
512 | 19.57 | 180 | 25.31 | 22.68% | -611.18% | 89.13%
1024 | 25.38 | 189.21 | 308.33 | 91.77% | 38.63% | 86.59%
2048 | 38.86 | 198.27 | 311.55 | 87.53% | 36.36% | 80.40%

2024-12-04 15:40 UTC, nsarka commented on src/components/cl/hier/Makefile.am
> -	allreduce/allreduce.h            \
Revert to tabs

2024-12-04 15:44 UTC, nsarka commented on test/gtest/coll/test_allgatherv.cc
> +        ::testing::Values(false, true)) // dst buf contig
::testing::bool

2024-12-04 16:07 UTC, nsarka commented on src/components/cl/hier/allgatherv/allgatherv.c
> +        args.args.flags            |= UCC_COLL_ARGS_FLAG_IN_PLACE;
remove in place

2024-12-04 16:15 UTC, nsarka commented on src/components/cl/hier/allgatherv/allgatherv.c
> +    if (SBGP_ENABLED(cl_team, NODE) &&
Add comment that if using tl shm, check that seg size / team size > msg size

2024-12-04 16:16 UTC, nsarka commented on src/components/cl/hier/allgatherv/unpack.c
> +    schedule->super.flags |= UCC_COLL_TASK_FLAG_EXECUTOR;
Alignment

2024-12-04 16:32 UTC, nsarka commented on src/components/cl/hier/allgatherv/allgatherv.c
> +                ucc_cl_hier_allgatherv_unpack_init(&args, team, &tasks[n_tasks]),
change to use another scratch buffer instead of inplace unpack

2024-12-04 16:33 UTC, nsarka commented on src/components/cl/hier/allgatherv/allgatherv.c
> +        args.args.flags                   &= ~UCC_COLL_ARGS_FLAG_IN_PLACE;
add flag for contig

2024-12-07 04:21 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2024-12-11 17:44 UTC, manjugv commented
@aamirshafi  Please review

2025-01-24 14:21 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/allgatherv.c
> +UCC_CL_HIER_PROFILE_FUNC(ucc_status_t, ucc_cl_hier_allgatherv_init,
return unsupported error if memory type is not host

2025-01-24 14:21 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/unpack.c
> +    int                         i;
int -> ucc_rank_t

2025-01-24 14:21 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/unpack.c
> +    schedule->super.super.status = UCC_INPROGRESS;
no need to set super.super.status

2025-01-24 14:21 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/unpack.c
> +    schedule->super.super.status = st;
don't set it, it may lead to races with multiple threads

2025-01-24 14:21 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/unpack.c
> +        ucc_ee_executor_task_t *etask = tasks[i];
define variable at the beginning of function

2025-01-24 14:21 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/unpack.c
> +                                                         ucc_cl_hier_schedule_t);
```suggestion
    ucc_cl_hier_schedule_t *cl_schedule = ucc_derived_of(task,
                                                         ucc_cl_hier_schedule_t);
```

2025-01-24 16:17 UTC, janjust requested changes

2025-02-11 22:23 UTC, nsarka commented on src/components/cl/hier/allgatherv/allgatherv.c
> +        args.args.dst.info_v.buffer        = args_old.args.dst.info_v.buffer;
why would there be gaps in this buffer? The gatherv will remove them and place the data into `args.args.dst.info_v.buffer` contiguously

2025-02-12 16:40 UTC, nsarka commented on src/components/cl/hier/cl_hier_team.c
> +    status = ucc_coll_score_add_range(
it would add all mem_types to the score, wouldn't it? We only want allgatherv to support host

2025-02-26 09:19 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/allgatherv.c
> +UCC_CL_HIER_PROFILE_FUNC(ucc_status_t, ucc_cl_hier_allgatherv_init,
i think it's inefficient

2025-02-26 09:22 UTC, Sergei-Lebedev commented on src/components/cl/hier/cl_hier_team.c
> +    status = ucc_coll_score_add_range(
it depends how default select str is defined, if you add host memtype to it then for cuda allgatherv it will not be selected

2025-02-26 09:26 UTC, Sergei-Lebedev approved these changes

2025-02-26 09:26 UTC, Sergei-Lebedev commented on src/components/cl/hier/allgatherv/allgatherv.c
> +                                          ucc_rank_t        *rank_out)
alignment

2025-03-05 17:29 UTC, wfaderhold21 approved these changes

2025-03-13 21:29 UTC, merged