TL/UCP: add reduce srg knomial
openucx/ucc pull request #1058
Opened 2024-12-18 12:26 UTC by Sergei-Lebedev

## What
Add reduce srg knomial algorithm to TL UCP

## Why ?
Improves performance of large msg reduce collective

## How ?
Implemented as schedule of reduce scatter knomial followed by gather knomial

2024-12-18 16:44 UTC, Sergei-Lebedev commented on src/components/tl/ucp/Makefile.am
> +    reduce/reduce_srg_knomial.c
alignment

2024-12-18 16:44 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
> +        ucc_kn_rsx_pattern_init(size, VRANK(rank, coll_args->args.root, size),
add reordering for reduce

2024-12-18 16:44 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce/reduce_srg_knomial.c
> +    /* 1st step of reduce: knomial reduce_scatter */
move comment up

2024-12-18 16:44 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce/reduce_srg_knomial.c
> +    radix     = ucc_knomial_pattern_get_min_radix(cfg_radix,
add tl_trace

2024-12-18 16:44 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce/reduce_srg_knomial.c
> +
rem empty line

2025-01-30 21:43 UTC, MamziB commented on src/components/tl/ucp/reduce/reduce_srg_knomial.c
> +        st = ucc_mc_alloc(&schedule->scratch_mc_header, count * dt_size, mt);
Can you avoid the scratch buffer allocation? For example, in the first call of this collective algorithm, allocate a large enough buffer for this team, and reuse this scratch buffer for the future calls into this collective again.

2025-01-30 21:48 UTC, MamziB commented on src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
>          peer = ucc_ep_map_eval(task->subset.map,
I see that in many places we are trying to find out the actual peer. Can you add a function call that unifies all these ```VRANK/INV_VRANK/ucc_ep_map_eval``` calls into a ```knomial_get_actual_peer()``` and use this function instead?

2025-01-30 21:49 UTC, MamziB commented
@Sergei-Lebedev very solid PR, Thanks for creating this new SRG reduce algorithm. Please see my comments.

2025-02-06 12:36 UTC, samnordmann approved these changes
I reviewed https://github.com/openucx/ucc/pull/1035 directly

2025-02-19 17:09 UTC, janjust requested changes
I let minor comments here and there - overall it's great, just stylist things

2025-03-10 10:29 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce/reduce_srg_knomial.c
> +                   out, status);
it's just to indicate that out and status are part of UCC_CHECK_GOTO macro, we use such alignment in many places

2025-03-10 10:30 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce/reduce_srg_knomial.c
> +        st = ucc_mc_alloc(&schedule->scratch_mc_header, count * dt_size, mt);
No. Scratch space is shared between TLs and CLs and there is also fast scratch allocation pool. If some team doesn't return scratch back to that pool we will run out of fast allocation cache pretty quickly.

2025-03-10 14:31 UTC, Sergei-Lebedev commented on src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
>          peer = ucc_ep_map_eval(task->subset.map,
done

2025-03-18 19:26 UTC, janjust approved these changes

2025-03-28 20:38 UTC, janjust commented
bot:retest

2025-04-01 16:48 UTC, artemry-nv commented
bot:retest

2025-04-04 05:59 UTC, merged