MC/CUDA: fp16 reduce
openucx/ucc pull request #224
Opened 2021-06-16 13:15 UTC by Sergei-Lebedev

## What
Added support for UCC_DT_FLOAT16 in cuda memory component

2021-06-16 14:10 UTC, vspetrov requested changes
gtest?

2021-06-16 14:10 UTC, vspetrov commented on src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
> +            ucc_assert(4 == sizeof(__half));
4->2

2021-06-16 14:16 UTC, Sergei-Lebedev commented on src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
> +            ucc_assert(4 == sizeof(__half));
copy paste 🤦‍♂️

2021-06-16 16:50 UTC, Sergei-Lebedev commented
> gtest?

it would not be easy to add, need conversion functions from fp16 to fp32 and back as well as some function that will check fp16 accuracy for fp32 numbers. There are intrinsics for some cpu arch but then we need config time detection for it. Overall it seems that test will be overcomplicated and we will need tests for test

2021-06-17 06:41 UTC, vspetrov commented
> > gtest?
> 
> it would not be easy to add, need conversion functions from fp16 to fp32 and back as well as some function that will check fp16 accuracy for fp32 numbers. There are intrinsics for some cpu arch but then we need config time detection for it. Overall it seems that test will be overcomplicated and we will need tests for test

i meant for GPU, we do test mc reduce for GPU right? we can postpone it for later

2021-06-17 06:41 UTC, vspetrov approved these changes

2021-06-21 16:11 UTC, manjugv approved these changes

2021-06-22 06:18 UTC, merged