UTILS: Add ucs machine id
openucx/ucc pull request #286
Opened 2021-08-10 11:21 UTC by lappazos

## What
Add use of UCS ucs_get_system_id in proc_info 

## Why ?
More accurate machine id in various cases

## How ?
Check for function existence in UCS, is yes - use it, else keep same.

2021-08-10 11:30 UTC, lappazos commented
according to PR https://github.com/openucx/ucx/pull/7180

2021-08-10 13:10 UTC, vspetrov commented on src/utils/ucc_proc_info.c
> +#include "config.h"
i remember we decided to put all the UCS stuff to utils. So, lets create ucc_get_system_id function, and implement it there via ucs_get_system_id.

2021-08-10 14:51 UTC, vspetrov requested changes

2021-08-10 14:51 UTC, vspetrov commented on src/utils/ucc_proc_info.c
> +#ifdef HAVE_UCS_GET_SYSTEM_ID
don't need ifdef here

2021-08-10 16:32 UTC, bureddy commented on config/m4/ucx.m4
> +            [],[-luct -lucm -lucp])
is "ucm" "ucp"  needed here?

2021-08-10 16:32 UTC, bureddy approved these changes

2021-08-10 16:42 UTC, vspetrov approved these changes

2021-08-11 15:33 UTC, manjugv commented
@lappazos There are some CI errors. Do you have details for it?

2021-08-11 16:12 UTC, lappazos commented
Waits for https://github.com/openucx/ucc/pull/287 in order to pass tests

2021-08-11 16:13 UTC, lappazos commented
> @lappazos There are some CI errors. Do you have details for it?
Waits for #287 in order to pass tests

2021-08-12 11:05 UTC, lappazos commented on config/m4/ucx.m4
> +            [],[-luct -lucm -lucp])
it won't hurt, but might prevent errors

2021-08-12 13:53 UTC, merged