TL/SHARP: sharp coll context/tree  per team
openucx/ucc pull request #626
Opened 2022-09-14 19:11 UTC by bureddy

Option to use sharp coll context(tree/job) per team ( similar NCCL SHARP model)

2022-09-21 20:36 UTC, vspetrov requested changes
Copyrights 2022

2022-09-21 20:36 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp.c
> +     "Number of polls to do before calling user progress",
Incorrect parameter description

2022-09-21 20:36 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_coll.c
> +        sharp_ctx = ctx->sharp_context;
maybe always set team->sharp_ctx during team creation. If CTX_PER_TEAM is not set then the ptr will point to global context. Then you don't need these branches, and the ucc_tl_sharp_mem_register can just take team

2022-09-21 20:36 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_context.c
>      init_spec.group_channel_idx              = 0;
duplicate of group_channel_idx?

2022-09-21 20:36 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_context.c
> +    if (sharp_ctx->cfg.context_per_team) {
why not making this check before line 398?

2022-09-21 20:36 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_team.c
> +    struct sharp_coll_context      *sharp_ctx = ctx->sharp_context;
initialized vars go first

2022-09-21 20:36 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_coll.c
> +        rcache = team->rcache;
align =

2022-09-21 20:37 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_coll.c
> +    ucc_rcache_t *rcache;
align local vars declarations

2022-09-21 20:37 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_coll.c
> +        sharp_ctx = ctx->sharp_context;
align =

2022-09-21 20:39 UTC, vspetrov commented on src/components/tl/sharp/tl_sharp_team.c
> +    self->sharp_context = NULL;
align =

2022-09-28 05:14 UTC, bureddy commented
bot:retest

2022-09-28 13:35 UTC, vspetrov approved these changes

2022-10-03 22:28 UTC, manjugv approved these changes

2022-10-04 08:56 UTC, Sergei-Lebedev approved these changes

2022-10-04 11:04 UTC, merged