TEST: add configurable dt for non-reduction colls
openucx/ucc pull request #707
Opened 2023-01-04 15:08 UTC by samnordmann

2023-02-06 10:08 UTC, shimmybalsam requested changes

2023-02-06 10:08 UTC, shimmybalsam commented on test/mpi/test_alltoall.cc
> +    size_t      dt_size           = ucc_dt_size(dt);
alignment

2023-02-06 10:08 UTC, shimmybalsam commented on test/mpi/test_mpi.h
> +    ucc_datatype_t dt;
not needed as is protected in parent class. same for all collectives.

2023-02-07 13:08 UTC, shimmybalsam approved these changes

2023-02-07 13:08 UTC, shimmybalsam commented on test/mpi/test_mpi.h
> +bool ucc_coll_has_datatype(ucc_coll_type_t c);
perhaps should be changed to int similar to inplace_supported and is_rooted?

2023-02-14 12:45 UTC, vspetrov approved these changes

2023-02-22 07:04 UTC, Sergei-Lebedev approved these changes

2023-02-22 12:31 UTC, merged